id: I793F972D
legacy_id: P009490
ocr_import_info:
  bdrc_scan_id: W4CZ30702
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T09:33:49'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T18:30:57.703737+00:00'
last_modified: 2022-09-04 02:31:16.765555
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ30702
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ30702
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ས་སྐྱའི་གདུང་རབས་ཆེན་མོ།
  author: འཇམ་མགོན་ཨ་མེས་ཞབས།
statistics:
  ocr_word_mean_confidence_index: 0.5440170676815373
  ocr_word_median_confidence_index: 0.5199999809265137
quality: null
bases:
  I4CZ30704:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ30704
      total_pages: 528
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ30704.txt
    statistics:
      ocr_word_median_confidence_index: 0.5199999809265137
      ocr_word_mean_confidence_index: 0.5440170676815373
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
