id: P009490
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ30702
  title: ས་སྐྱའི་གདུང་རབས་ཆེན་མོ།
  author: ''
  volumes:
    119e8c89233f46cc884644516ac8d2ec:
      image_group_id: I4CZ30704
      title: ''
      volume_number: 1
      total_pages: 528
      base_file: v001.txt
